#!/usr/bin/env cmsRun
import FWCore.ParameterSet.Config as cms

process = cms.Process("VBFMCH4jAnalysis")

process.load("SimGeneral.HepPDTESSource.pythiapdt_cfi")

process.load('Configuration/StandardSequences/Services_cff')
process.load("FWCore.MessageService.MessageLogger_cfi")
process.MessageLogger.cerr.threshold = 'INFO'


# Source
process.maxEvents = cms.untracked.PSet(input = cms.untracked.int32(-1))

process.source = cms.Source(
    "PoolSource",
    debugFlag = cms.untracked.bool(True),
    debugVebosity = cms.untracked.uint32(1),
    fileNames = cms.untracked.vstring(
   
   'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_1.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_100.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_101.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_102.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_103.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_104.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_105.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_106.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_107.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_108.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_109.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_11.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_110.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_111.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_112.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_113.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_114.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_115.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_116.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_117.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_118.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_119.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_12.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_120.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_121.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_122.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_123.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_124.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_126.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_127.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_128.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_129.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_13.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_130.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_131.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_132.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_133.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_134.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_135.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_136.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_137.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_138.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_139.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_14.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_140.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_141.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_142.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_143.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_144.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_145.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_146.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_147.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_148.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_149.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_15.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_150.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_151.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_152.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_153.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_154.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_155.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_156.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_157.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_158.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_159.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_16.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_160.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_161.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_162.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_163.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_164.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_165.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_166.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_167.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_168.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_169.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_17.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_170.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_171.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_172.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_173.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_174.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_175.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_176.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_177.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_178.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_179.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_18.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_180.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_181.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_182.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_183.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_184.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_186.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_187.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_188.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_189.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_19.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_190.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_191.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_192.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_193.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_194.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_195.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_196.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_197.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_198.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_199.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_2.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_20.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_200.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_21.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_22.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_23.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_24.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_25.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_26.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_27.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_28.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_29.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_3.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_30.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_31.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_32.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_33.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_34.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_35.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_36.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_37.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_38.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_39.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_4.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_40.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_41.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_42.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_43.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_44.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_45.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_46.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_47.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_48.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_49.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_5.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_50.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_51.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_52.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_53.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_54.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_55.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_56.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_57.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_58.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_59.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_6.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_60.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_61.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_62.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_63.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_64.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_65.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_66.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_67.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_68.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_69.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_7.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_70.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_71.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_72.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_73.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_74.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_75.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_76.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_77.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_78.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_79.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_8.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_80.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_81.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_82.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_83.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_84.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_85.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_86.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_87.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_88.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_89.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_9.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_90.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_91.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_92.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_93.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_94.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_95.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_96.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_97.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_98.root',
'rfio:/castor/cern.ch/user/a/amassiro/VBF/MySample/qqHWW_jjjj/H130/CMSSWfile_99.root'
   
       )
    )

 


# Dump MC information


process.VBFMCH4jAnalysis = cms.EDAnalyzer(
    "VBFMCH4jAnalysis",
    srcHepMCProduct = cms.InputTag("source"),
    srcGenParticles = cms.InputTag("genParticles"),
    srcGenMet = cms.InputTag("genMetNoNuBSM"),
    srcIC5GenJets = cms.InputTag("iterativeCone5GenJets"),
    srcIC5CaloJets = cms.InputTag("iterativeCone5CaloJets"),
    fileName = cms.untracked.string("VBFMCDump"),
    mass = cms.string("300"),
    verbosity = cms.untracked.bool(True),
    eventsToPrint = cms.untracked.int32(1)
    )


process.VBFMCH4jAnalysis.fileName = "VBFMCDumper_H4j"
process.VBFMCH4jAnalysis.mass = "130"
process.VBFMCH4jAnalysis.verbosity = False
process.VBFMCH4jAnalysis.eventsToPrint = 0

process.p0 = cms.Path(process.VBFMCH4jAnalysis)

process.schedule = cms.Schedule(process.p0)
