#perl makeConfigsVBFplots.pl H160 HiggsAnalysis/VBFHiggsToWW2e/data/datasets/MIB_skim_H160.cfi
perl makeConfigsVBFplots.pl WWF HiggsAnalysis/VBFHiggsToWW2e/data/datasets/MIB_skim_H160.cfi
perl makeConfigsVBFplots.pl ggF HiggsAnalysis/VBFHiggsToWW2e/data/datasets/MIB_skim_H160.cfi
perl makeConfigsVBFplots.pl Wt HiggsAnalysis/VBFHiggsToWW2e/data/datasets/MIB_skim_Wt.cfi  
perl makeConfigsVBFplots.pl WW HiggsAnalysis/VBFHiggsToWW2e/data/datasets/MIB_skim_WW.cfi
perl makeConfigsVBFplots.pl WZ HiggsAnalysis/VBFHiggsToWW2e/data/datasets/MIB_skim_WZ.cfi
perl makeConfigsVBFplots.pl WZ_incl HiggsAnalysis/VBFHiggsToWW2e/data/datasets/MIB_skim_WZ_incl.cfi
perl makeConfigsVBFplots.pl ZZ_incl HiggsAnalysis/VBFHiggsToWW2e/data/datasets/MIB_skim_ZZ_incl.cfi
perl makeConfigsVBFplots.pl tt0j HiggsAnalysis/VBFHiggsToWW2e/data/datasets/MIB_skim_tt0j.cfi
perl makeConfigsVBFplots.pl tt1j HiggsAnalysis/VBFHiggsToWW2e/data/datasets/MIB_skim_tt1j.cfi
perl makeConfigsVBFplots.pl tt2j HiggsAnalysis/VBFHiggsToWW2e/data/datasets/MIB_skim_tt2j.cfi
perl makeConfigsVBFplots.pl tt3j HiggsAnalysis/VBFHiggsToWW2e/data/datasets/MIB_skim_tt3j.cfi
perl makeConfigsVBFplots.pl tt4j HiggsAnalysis/VBFHiggsToWW2e/data/datasets/MIB_skim_tt4j.cfi
