#perl makeConfigsVBFplots.pl H160 HiggsAnalysis/VBFHiggsToWW2e/data/datasets/MIB_skim_H160.cfi
perl makeConfigsVBFplots.pl H160 HiggsAnalysis/VBFHiggsToWW2e/data/datasets/MIB_skim_Wt.cfi  
perl makeConfigsVBFplots.pl H160 HiggsAnalysis/VBFHiggsToWW2e/data/datasets/MIB_skim_WW.cfi
perl makeConfigsVBFplots.pl H160 HiggsAnalysis/VBFHiggsToWW2e/data/datasets/MIB_skim_WZ.cfi
perl makeConfigsVBFplots.pl H160 HiggsAnalysis/VBFHiggsToWW2e/data/datasets/MIB_skim_WZ_incl.cfi
perl makeConfigsVBFplots.pl H160 HiggsAnalysis/VBFHiggsToWW2e/data/datasets/MIB_skim_ZZ_incl.cfi
perl makeConfigsVBFplots.pl H160 HiggsAnalysis/VBFHiggsToWW2e/data/datasets/MIB_skim_tt0j.cfi
perl makeConfigsVBFplots.pl H160 HiggsAnalysis/VBFHiggsToWW2e/data/datasets/MIB_skim_tt1j.cfi
perl makeConfigsVBFplots.pl H160 HiggsAnalysis/VBFHiggsToWW2e/data/datasets/MIB_skim_tt2j.cfi
perl makeConfigsVBFplots.pl H160 HiggsAnalysis/VBFHiggsToWW2e/data/datasets/MIB_skim_tt3j.cfi
perl makeConfigsVBFplots.pl H160 HiggsAnalysis/VBFHiggsToWW2e/data/datasets/MIB_skim_tt4j.cfi
