
//.x /Users/govoni/public/rootLogon.C
//TFile *_file0 = TFile::Open ("testVBFIsolation.root") ;
//testIsol->cd () ;
TCanvas c1 ;
TH2F * dummy = new TH2F ("dummy","",3.15,0,3.15,2,0.3,2) ;
dummy->SetStats (0) ;
dummy->Draw () ;
dummy->GetXaxis ()->SetTitle ("#Delta #phi") ;
OLDIsoEffvsDPhi->RebinX (6) ;
TProfile * pOLD = OLDIsoEffvsDPhi->ProfileX () ;
pOLD->SetMarkerStyle (20) ;
pOLD->SetMarkerColor (65) ;
pOLD->Draw ("same") ;
NEWIsoEffvsDPhi->RebinX (6) ;
TProfile * pNEW = NEWIsoEffvsDPhi->ProfileX () ;
pNEW->SetMarkerStyle (25) ;
pNEW->SetMarkerColor (98) ;
pNEW->Draw ("same") ;
pOLD->GetXaxis ()->SetTitle ("#Delta #phi") ;
TLegend  * l1 = new TLegend ( 0.6, 0.2, 0.9, 0.4) ;
l1->AddEntry (pOLD, "ISO with cones", "lmp") ;
l1->AddEntry (pNEW, "ISO without cones", "lmp") ;
l1->Draw () ;
TCanvas c3 ;
TH1D * yOLD = OLDIsoEffvsDPhi->ProjectionY () ;
TH1D * yNEW = NEWIsoEffvsDPhi->ProjectionY () ;
yOLD->SetMarkerStyle (20) ;
yOLD->SetMarkerColor (65) ;
yNEW->SetMarkerStyle (25) ;
yNEW->SetMarkerColor (98) ;
yOLD->Rebin (10) ;
yNEW->Rebin (10) ;
yOLD->DrawNormalized ("P") ;
yNEW->DrawNormalized ("Psame") ;

TH2F * dummy2 = new TH2F ("dummy2","",3,0.,3.,10,0.,1.) ;
dummy2->SetStats (0) ;
dummy2->Draw () ;
dummy2->GetXaxis ()->SetTitle ("isol ele") ;
dummy2->GetYaxis ()->SetTitle ("eff") ;
yOLD->DrawNormalized ("Psame") ;
yNEW->DrawNormalized ("Psame") ;
l1->Draw () ;

TCanvas c2 ;
c2->SetLogy () ;
NEWIsoValue->Rebin (8) ;
NEWIsoValue->SetFillColor (4) ;
NEWIsoValue->Draw () ;

TCanvas c1 ;
c1->SetLogy () ;
NEWIsoValueW->SetLineWidth (2) ;
NEWIsoValueW->SetLineColor (2) ;
NEWIsoValueW->SetLineStyle (7) ;
NEWIsoValueWO->SetLineWidth (2) ;
NEWIsoValueWO->SetLineColor (4) ;
NEWIsoValueWO->Rebin (8) ;
NEWIsoValueW->Rebin (8) ;
NEWIsoValueW->Draw () ;
NEWIsoValueWO->Draw ("same") ;
TLegend  * l2 = new TLegend ( 0.4, 0.6, 0.9, 0.9) ;
l2->AddEntry (NEWIsoValueW, "with additional cone", "l") ;
l2->AddEntry (NEWIsoValueWO, "wo additional cone", "l") ;
l2->Draw () ;
